Edit user guide
AY2425S1-CS2103T-F09-1/tp pull request #168
Opened 2024-11-07 12:14 UTC by LiHaixin000

Fixes #167

2024-11-07 13:04 UTC, limyixiang requested changes

2024-11-07 13:04 UTC, limyixiang commented on docs/UserGuide.md
> +* At least one of the optional fields (EVENT_NAME, EVENT_DESCRIPTION, EVENT_START_DATE, EVENT_END_DATE) must be provided to make changes.
Please surround EVENT_NAME, EVENT_DESCRIPTION, EVENT_START_DATE, EVENT_END_DATE with ` on each of them to be coherent with the rest of the user guide.

2024-11-08 05:22 UTC, G-Y-Chan approved these changes
LGTM!

2024-11-08 05:22 UTC, G-Y-Chan commented on docs/UserGuide.md
LGTM!

2024-11-08 05:23 UTC, merged